# Generated by GPT on 2026-02-24

from django.db import migrations, models


def create_ramadan_catalog(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    Product = apps.get_model("catalog", "Product")

    # Hide any previous demo/old catalog without breaking existing orders
    Category.objects.all().update(is_active=False)
    Product.objects.all().update(is_active=False)

    categories = [
        {
            "name": "Pâtisseries feuilletées",
            "slug": "patisseries-feuilletees",
            "description": "Feuilletés au beurre, miel et fruits secs — parfaits pour l’iftar.",
        },
        {
            "name": "Kunafa & fromages",
            "slug": "kunafa-fromages",
            "description": "Kunafa dorée, fromage fondant et sirop parfumé (fleur d’oranger).",
        },
        {
            "name": "Gâteaux de semoule",
            "slug": "gateaux-de-semoule",
            "description": "Textures moelleuses, sirop léger, amandes et notes de rose.",
        },
        {
            "name": "Maamoul & biscuits",
            "slug": "maamoul-biscuits",
            "description": "Biscuits sablés fourrés (dattes, pistaches, noix) — tradition Ramadan.",
        },
        {
            "name": "Desserts du Ramadan",
            "slug": "desserts-ramadan",
            "description": "Sélection spéciale Ramadan : qatayef, douceurs à partager et coffrets.",
        },
        {
            "name": "Dattes & noix",
            "slug": "dattes-noix",
            "description": "Dattes premium, fourrées et enrobées — énergie douce après le jeûne.",
        },
        {
            "name": "Boissons & sirops",
            "slug": "boissons-sirops",
            "description": "Sirops et boissons traditionnelles (caroube, dattes, rose) pour l’iftar.",
        },
    ]

    category_by_slug = {}
    for c in categories:
        obj, _ = Category.objects.update_or_create(
            slug=c["slug"],
            defaults={
                "name": c["name"],
                "description": c["description"],
                "is_active": True,
            },
        )
        category_by_slug[c["slug"]] = obj

    products = [
        {
            "name": "Baklawa pistache — coffret 12 pièces",
            "slug": "baklawa-pistache-12",
            "category_slug": "patisseries-feuilletees",
            "description": "Baklawa feuilletée, pistaches torréfiées, sirop léger au miel. Idéal à offrir pendant Ramadan.",
            "price": "18.90",
            "stock": 40,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Baklava_-_Turkish_special,_80-ply.JPEG",
        },
        {
            "name": "Kunafa Nabulsi — pistache",
            "slug": "kunafa-nabulsi-pistache",
            "category_slug": "kunafa-fromages",
            "description": "Kunafa croustillante, fromage fondant, pistaches et touche de fleur d’oranger.",
            "price": "14.50",
            "stock": 25,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a1/Kunafa.jpg",
        },
        {
            "name": "Basbousa aux amandes",
            "slug": "basbousa-amandes",
            "category_slug": "gateaux-de-semoule",
            "description": "Gâteau de semoule moelleux, sirop parfumé, amandes entières. Douceur classique du Moyen‑Orient.",
            "price": "9.90",
            "stock": 35,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Basbousa2.JPG",
        },
        {
            "name": "Maamoul dattes — boîte",
            "slug": "maamoul-dattes",
            "category_slug": "maamoul-biscuits",
            "description": "Biscuits sablés fondants, fourrés à la pâte de dattes. Parfait avec un café arabe après l’iftar.",
            "price": "12.50",
            "stock": 50,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/96/Date_Maamul%2C_Pistachio_Baklava_and_Coffee_-_Moroccan_Soup_Bar.jpg",
        },
        {
            "name": "Qatayef — assortiment (crème & noix)",
            "slug": "qatayef-assortiment",
            "category_slug": "desserts-ramadan",
            "description": "Qatayef traditionnels : garniture crème (ashta) et mélange de noix, finitions pistache.",
            "price": "13.50",
            "stock": 20,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/f2/WMCON18_by_Rehman_-_Sweets_Table_%281%29.jpg",
        },
        {
            "name": "Om Ali — dessert du four",
            "slug": "om-ali",
            "category_slug": "desserts-ramadan",
            "description": "Dessert chaud au lait, pâte feuilletée et fruits secs. Confort absolu après une journée de jeûne.",
            "price": "7.90",
            "stock": 18,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Om_ali.jpg",
        },
        {
            "name": "Dattes Majhoul fourrées amandes",
            "slug": "dattes-majhoul-amandes",
            "category_slug": "dattes-noix",
            "description": "Dattes Majhoul moelleuses, fourrées aux amandes. À déguster à l’iftar ou en cadeau.",
            "price": "11.90",
            "stock": 60,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Dattes_Majhoul_four%C3%A9es.jpg",
        },
        {
            "name": "Jallab — sirop dattes & caroube",
            "slug": "jallab-sirop",
            "category_slug": "boissons-sirops",
            "description": "Sirop traditionnel (caroube, dattes, mélasse de raisin, rose). À diluer frais, parfait pour Ramadan.",
            "price": "6.50",
            "stock": 80,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/34/Jallab.jpg",
        },
    ]

    for p in products:
        Product.objects.update_or_create(
            slug=p["slug"],
            defaults={
                "category": category_by_slug[p["category_slug"]],
                "name": p["name"],
                "description": p["description"],
                "price": p["price"],
                "stock": p["stock"],
                "is_active": True,
                "image_url": p["image_url"],
            },
        )


def noop_reverse(apps, schema_editor):
    # Intentionally no-op: we don't want to delete products when rolling back,
    # as orders may reference them (PROTECT).
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_demo_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.RunPython(create_ramadan_catalog, reverse_code=noop_reverse),
    ]

