from django.core.management.base import BaseCommand


RAMADAN_CATEGORIES = [
    {
        "name": "Pâtisseries feuilletées",
        "slug": "patisseries-feuilletees",
        "description": "Feuilletés au beurre, miel et fruits secs — parfaits pour l'iftar.",
    },
    {
        "name": "Kunafa & fromages",
        "slug": "kunafa-fromages",
        "description": "Kunafa dorée, fromage fondant et sirop parfumé (fleur d'oranger).",
    },
    {
        "name": "Gâteaux de semoule",
        "slug": "gateaux-de-semoule",
        "description": "Textures moelleuses, sirop léger, amandes et notes de rose.",
    },
    {
        "name": "Maamoul & biscuits",
        "slug": "maamoul-biscuits",
        "description": "Biscuits sablés fourrés (dattes, pistaches, noix) — tradition Ramadan.",
    },
    {
        "name": "Desserts du Ramadan",
        "slug": "desserts-ramadan",
        "description": "Sélection spéciale Ramadan : qatayef, douceurs à partager et coffrets.",
    },
    {
        "name": "Dattes & noix",
        "slug": "dattes-noix",
        "description": "Dattes premium, fourrées et enrobées — énergie douce après le jeûne.",
    },
    {
        "name": "Boissons & sirops",
        "slug": "boissons-sirops",
        "description": "Sirops et boissons traditionnelles (caroube, dattes, rose) pour l'iftar.",
    },
    {
        "name": "Jus frais Ramadan",
        "slug": "jus-frais",
        "description": "Boissons fraîches (citron & menthe, tamarin…) — parfaites à l'iftar.",
    },
    {
        "name": "Chocolat",
        "slug": "chocolat",
        "description": "Chocolats et douceurs au cacao — à offrir ou à déguster à l'iftar.",
    },
]

# Images: Pexels (format w=1200) et Unsplash pour un rendu très appétissant
RAMADAN_PRODUCTS = [
    # Pâtisseries feuilletées
    {
        "name": "Baklawa pistache — coffret 12 pièces",
        "slug": "baklawa-pistache-12",
        "category_slug": "patisseries-feuilletees",
        "description": "Baklawa feuilletée dorée, généreusement garnie de pistaches torréfiées, sirop au miel. À offrir pendant Ramadan.",
        "price": "18.90",
        "stock": 40,
        "image_url": "/catalog/baklawa_pistache_12.png",
    },
    {
        "name": "Baklawa mix — pistache & noix",
        "slug": "baklawa-mix-pistache-noix",
        "category_slug": "patisseries-feuilletees",
        "description": "Assortiment feuilleté (pistache & noix), sirop léger, finition pistache concassée. Coffret prestige.",
        "price": "21.90",
        "stock": 28,
        "image_url": "https://images.pexels.com/photos/30672435/pexels-photo-30672435.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Baklawa noix — coffret 10 pièces",
        "slug": "baklawa-noix-10",
        "category_slug": "patisseries-feuilletees",
        "description": "Feuilletés aux noix et au miel, dorés au four. Texture croustillante et fondant en bouche.",
        "price": "16.50",
        "stock": 35,
        "image_url": "/catalog/baklawa_noix_10_pieces.png",
    },
    {
        "name": "Assortiment baklawa prestige — 3 variétés",
        "slug": "assortiment-baklawa-prestige",
        "category_slug": "patisseries-feuilletees",
        "description": "Pistache, noix et amandes — trois variétés dans un coffret cadeau. Parfait pour l'iftar en famille.",
        "price": "24.90",
        "stock": 22,
        "image_url": "/catalog/baklawa_3_sort.png",
    },
    {
        "name": "Baklawa amandes — coffret 8 pièces",
        "slug": "baklawa-amandes-8",
        "category_slug": "patisseries-feuilletees",
        "description": "Feuilletés aux amandes et miel, dorés et parfumés. Indémodable de la pâtisserie orientale.",
        "price": "17.90",
        "stock": 32,
        "image_url": "https://images.pexels.com/photos/7129411/pexels-photo-7129411.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Samoussa sucré — pistache & miel",
        "slug": "samoussa-sucre-pistache",
        "category_slug": "patisseries-feuilletees",
        "description": "Feuilleté en triangle, garniture pistache et miel. Croquant et fondant, parfait à l'iftar.",
        "price": "14.50",
        "stock": 38,
        "image_url": "/catalog/samoussa_pistache_miel.png",
    },
    # Kunafa & fromages
    {
        "name": "Kunafa Nabulsi — pistache",
        "slug": "kunafa-nabulsi-pistache",
        "category_slug": "kunafa-fromages",
        "description": "Kunafa croustillante, fromage fondant, pistaches et touche de fleur d'oranger. Servie tiède.",
        "price": "14.50",
        "stock": 25,
        "image_url": "https://images.pexels.com/photos/6419600/pexels-photo-6419600.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Kunafa au fromage — extra",
        "slug": "kunafa-fromage-extra",
        "category_slug": "kunafa-fromages",
        "description": "Kunafa généreuse au fromage, sirop chaud, pistaches. L'icône des soirées Ramadan.",
        "price": "16.90",
        "stock": 18,
        "image_url": "https://images.pexels.com/photos/10038701/pexels-photo-10038701.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Kunafa crème & pistache",
        "slug": "kunafa-creme-pistache",
        "category_slug": "kunafa-fromages",
        "description": "Kunafa fine, crème légère (ashta) et pistaches. Une version plus douce, tout aussi addictive.",
        "price": "15.90",
        "stock": 20,
        "image_url": "https://images.pexels.com/photos/7129411/pexels-photo-7129411.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Kunafa individuelle — portion",
        "slug": "kunafa-individuelle",
        "category_slug": "kunafa-fromages",
        "description": "Part individuelle de kunafa au fromage, sirop et pistaches. Prête à réchauffer.",
        "price": "6.90",
        "stock": 40,
        "image_url": "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Kunafa noix & cannelle",
        "slug": "kunafa-noix-cannelle",
        "category_slug": "kunafa-fromages",
        "description": "Kunafa garnie de noix et cannelle, sirop à la fleur d'oranger. Variante délicieuse.",
        "price": "15.50",
        "stock": 22,
        "image_url": "https://images.pexels.com/photos/30672435/pexels-photo-30672435.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Assortiment kunafa — 6 parts",
        "slug": "assortiment-kunafa-6",
        "category_slug": "kunafa-fromages",
        "description": "Six parts de kunafa (fromage, crème, noix). Idéal pour partager à l'iftar.",
        "price": "22.90",
        "stock": 15,
        "image_url": "https://images.pexels.com/photos/30672435/pexels-photo-30672435.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    # Gâteaux de semoule
    {
        "name": "Basbousa aux amandes",
        "slug": "basbousa-amandes",
        "category_slug": "gateaux-de-semoule",
        "description": "Gâteau de semoule moelleux, sirop parfumé, amandes entières. Douceur classique du Moyen‑Orient.",
        "price": "9.90",
        "stock": 35,
        "image_url": "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Basbousa coco & amandes",
        "slug": "basbousa-coco-amandes",
        "category_slug": "gateaux-de-semoule",
        "description": "Semoule, noix de coco râpée et amandes. Texture fondante et parfum envoûtant.",
        "price": "10.50",
        "stock": 30,
        "image_url": "https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Basbousa à la rose",
        "slug": "basbousa-rose",
        "category_slug": "gateaux-de-semoule",
        "description": "Semoule au sirop parfumé à l'eau de rose, amandes effilées. Douceur florale.",
        "price": "10.90",
        "stock": 28,
        "image_url": "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Namoura — semoule au yaourt",
        "slug": "namoura-semoule-yaourt",
        "category_slug": "gateaux-de-semoule",
        "description": "Gâteau de semoule au yaourt, sirop et amandes. Moelleux et fondant.",
        "price": "9.50",
        "stock": 33,
        "image_url": "https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Basbousa portion individuelle",
        "slug": "basbousa-individuel",
        "category_slug": "gateaux-de-semoule",
        "description": "Part individuelle de basbousa, sirop et amandes. Parfait avec un café.",
        "price": "4.90",
        "stock": 50,
        "image_url": "https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Assortiment semoule — 6 parts",
        "slug": "assortiment-semoule-6",
        "category_slug": "gateaux-de-semoule",
        "description": "Six parts variées : basbousa, namoura, coco. Coffret pour l'iftar.",
        "price": "18.90",
        "stock": 20,
        "image_url": "https://images.pexels.com/photos/10038701/pexels-photo-10038701.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    # Maamoul & biscuits
    {
        "name": "Maamoul dattes — boîte",
        "slug": "maamoul-dattes",
        "category_slug": "maamoul-biscuits",
        "description": "Biscuits sablés fondants, fourrés à la pâte de dattes. Parfait avec un café arabe après l'iftar.",
        "price": "12.50",
        "stock": 50,
        "image_url": "https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Maamoul pistache — boîte",
        "slug": "maamoul-pistache",
        "category_slug": "maamoul-biscuits",
        "description": "Maamoul fourrés à la pistache, motif traditionnel. Croquants et fondants à la fois.",
        "price": "13.90",
        "stock": 40,
        "image_url": "https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Maamoul assortiment — dattes, pistache, noix",
        "slug": "maamoul-assortiment",
        "category_slug": "maamoul-biscuits",
        "description": "Coffret trois parfums : dattes, pistache et noix. La boîte idéale pour offrir.",
        "price": "16.90",
        "stock": 28,
        "image_url": "https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Maamoul noix — boîte",
        "slug": "maamoul-noix",
        "category_slug": "maamoul-biscuits",
        "description": "Biscuits sablés fourrés à la noix, motif traditionnel. Croquants et fondants.",
        "price": "13.50",
        "stock": 36,
        "image_url": "https://images.pexels.com/photos/7129411/pexels-photo-7129411.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Ghraybeh — biscuits au beurre",
        "slug": "ghraybeh-beurre",
        "category_slug": "maamoul-biscuits",
        "description": "Biscuits fondants au beurre et à la fleur d'oranger. Tradition du Ramadan.",
        "price": "11.90",
        "stock": 44,
        "image_url": "https://images.pexels.com/photos/6419600/pexels-photo-6419600.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    # Desserts du Ramadan
    {
        "name": "Qatayef — crème (ashta) & pistache",
        "slug": "qatayef-assortiment",
        "category_slug": "desserts-ramadan",
        "description": "Crêpes moelleuses fourrées à la crème (ashta), nappées de sirop et pistaches. Le must du Ramadan.",
        "price": "13.50",
        "stock": 20,
        "image_url": "https://images.pexels.com/photos/6419600/pexels-photo-6419600.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Qatayef noix & cannelle",
        "slug": "qatayef-noix-cannelle",
        "category_slug": "desserts-ramadan",
        "description": "Qatayef garnis de noix, cannelle et sirop à la fleur d'oranger. Servis tièdes.",
        "price": "12.90",
        "stock": 22,
        "image_url": "https://images.pexels.com/photos/7129411/pexels-photo-7129411.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Om Ali — dessert du four",
        "slug": "om-ali",
        "category_slug": "desserts-ramadan",
        "description": "Dessert chaud au lait, pâte feuilletée et fruits secs. Confort absolu après une journée de jeûne.",
        "price": "7.90",
        "stock": 18,
        "image_url": "https://images.pexels.com/photos/10038701/pexels-photo-10038701.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Halwa à la tahina — pot",
        "slug": "halwa-tahina",
        "category_slug": "desserts-ramadan",
        "description": "Halwa onctueux à la pâte de sésame (tahina), parfum vanille. À tartiner ou à déguster à la cuillère.",
        "price": "8.90",
        "stock": 45,
        "image_url": "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Coffret desserts Ramadan — 5 douceurs",
        "slug": "coffret-desserts-ramadan-5",
        "category_slug": "desserts-ramadan",
        "description": "Qatayef, halwa, om ali et deux autres douceurs. À partager en famille à l'iftar.",
        "price": "28.90",
        "stock": 15,
        "image_url": "https://images.pexels.com/photos/30672435/pexels-photo-30672435.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    # Dattes & noix
    {
        "name": "Dattes Majhoul fourrées amandes",
        "slug": "dattes-majhoul-amandes",
        "category_slug": "dattes-noix",
        "description": "Dattes Majhoul moelleuses, fourrées aux amandes. À déguster à l'iftar ou en cadeau.",
        "price": "11.90",
        "stock": 60,
        "image_url": "/catalog/dattes_chocolat_coulis.png",
    },
    {
        "name": "Dattes Ajwa — coffret prestige",
        "slug": "dattes-ajwa",
        "category_slug": "dattes-noix",
        "description": "Dattes Ajwa (Medina), réputées pour leur douceur. Coffret cadeau pour Ramadan.",
        "price": "19.90",
        "stock": 35,
        "image_url": "/catalog/coffret_dattes_fourrees.png",
    },
    {
        "name": "Coffret dattes & amandes",
        "slug": "coffret-dattes-amandes",
        "category_slug": "dattes-noix",
        "description": "Dattes premium et amandes grillées. L'association parfaite pour rompre le jeûne.",
        "price": "14.90",
        "stock": 42,
        "image_url": "/catalog/dattes_miel_pistache.png",
    },
    {
        "name": "Dattes fourrées noix de pécan",
        "slug": "dattes-fourrees-pecan",
        "category_slug": "dattes-noix",
        "description": "Dattes moelleuses fourrées à la noix de pécan. Gourmandise à l'iftar.",
        "price": "13.90",
        "stock": 48,
        "image_url": "/catalog/dattes_pecan_pistache.png",
    },
    {
        "name": "Mélange fruits secs Ramadan",
        "slug": "melange-fruits-secs-ramadan",
        "category_slug": "dattes-noix",
        "description": "Dattes, amandes, noix et noisettes. Sachet à partager pour rompre le jeûne.",
        "price": "9.90",
        "stock": 55,
        "image_url": "/catalog/plateau_fruits_secs.png",
    },
    # Boissons & sirops
    {
        "name": "Jallab — sirop dattes & caroube",
        "slug": "jallab-sirop",
        "category_slug": "boissons-sirops",
        "description": "Sirop traditionnel (caroube, dattes, mélasse de raisin, rose). À diluer frais, parfait pour Ramadan.",
        "price": "6.50",
        "stock": 80,
        "image_url": "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=1200",
    },
    {
        "name": "Qamar al-Din — abricot",
        "slug": "qamar-al-din",
        "category_slug": "boissons-sirops",
        "description": "Pâte d'abricot séchée à diluer. Boisson star de l'iftar, désaltérante et énergisante.",
        "price": "7.20",
        "stock": 55,
        "image_url": "https://images.unsplash.com/photo-1621506283937-a8f6a6d2e235?w=1200",
    },
    {
        "name": "Sirop de rose — bouteille",
        "slug": "sirop-rose",
        "category_slug": "boissons-sirops",
        "description": "Sirop à l'eau de rose, à diluer. Parfum délicat pour les soirées Ramadan.",
        "price": "8.50",
        "stock": 45,
        "image_url": "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=1200",
    },
    {
        "name": "Sirop de caroube — tradition",
        "slug": "sirop-caroube",
        "category_slug": "boissons-sirops",
        "description": "Sirop de caroube naturel, énergisant. À servir frais à l'iftar.",
        "price": "7.90",
        "stock": 50,
        "image_url": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=1200",
    },
    {
        "name": "Assortiment sirops Ramadan — 3 parfums",
        "slug": "assortiment-sirops-ramadan",
        "category_slug": "boissons-sirops",
        "description": "Jallab, rose et caroube. Trois bouteilles pour varier les boissons de l'iftar.",
        "price": "18.90",
        "stock": 25,
        "image_url": "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=1200",
    },
    {
        "name": "Sirop de grenade — bouteille",
        "slug": "sirop-grenade",
        "category_slug": "boissons-sirops",
        "description": "Sirop de grenade acidulé et doux. Rafraîchissant à l'iftar.",
        "price": "8.90",
        "stock": 40,
        "image_url": "https://images.unsplash.com/photo-1621506283937-a8f6a6d2e235?w=1200",
    },
    # Jus frais
    {
        "name": "Limonana — citron & menthe (frais)",
        "slug": "limonana-citron-menthe",
        "category_slug": "jus-frais",
        "description": "Citron pressé, menthe fraîche, glace pilée. Ultra rafraîchissant à l'iftar.",
        "price": "5.20",
        "stock": 120,
        "image_url": "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=1200",
    },
    {
        "name": "Tamar Hindi — jus de tamarin",
        "slug": "tamar-hindi-tamarin",
        "category_slug": "jus-frais",
        "description": "Jus de tamarin équilibré (acidulé & doux), servi bien frais — classique Ramadan.",
        "price": "5.50",
        "stock": 120,
        "image_url": "/catalog/tamar_hindi.png",
    },
    {
        "name": "Jus d'orange frais — bouteille",
        "slug": "jus-orange-frais",
        "category_slug": "jus-frais",
        "description": "Orange pressée du jour, sans sucre ajouté. Vitamine C et fraîcheur garanties.",
        "price": "4.90",
        "stock": 100,
        "image_url": "/catalog/jus_orange.png",
    },
    {
        "name": "Jus de pastèque frais",
        "slug": "jus-pasteque-frais",
        "category_slug": "jus-frais",
        "description": "Pastèque pressée, désaltérante. Incontournable des tables d'iftar.",
        "price": "5.90",
        "stock": 80,
        "image_url": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=1200",
    },
    {
        "name": "Smoothie mangue & dattes",
        "slug": "smoothie-mangue-dattes",
        "category_slug": "jus-frais",
        "description": "Mangue, dattes et yaourt. Énergie et douceur après le jeûne.",
        "price": "6.50",
        "stock": 60,
        "image_url": "/catalog/smoothie_mangue.png",
    },
    # Chocolat
    {
        "name": "Chocolats orientaux — pistache & amande",
        "slug": "chocolats-orientaux-pistache",
        "category_slug": "chocolat",
        "description": "Chocolat noir et lait garni de pistaches et amandes. Coffret cadeau Ramadan.",
        "price": "22.90",
        "stock": 30,
        "image_url": "/catalog/chocolats_pistache_amande.png",
    },
    {
        "name": "Truffes au cacao — boîte 12",
        "slug": "truffes-cacao-12",
        "category_slug": "chocolat",
        "description": "Truffes fondantes enrobées de cacao. Parfaites avec un café après l'iftar.",
        "price": "14.90",
        "stock": 45,
        "image_url": "/catalog/coffret_lune_fraise.png",
    },
    {
        "name": "Chocolat aux dattes — barre",
        "slug": "chocolat-dattes-barre",
        "category_slug": "chocolat",
        "description": "Chocolat noir et pâte de dattes. L'association star du Ramadan.",
        "price": "6.90",
        "stock": 80,
        "image_url": "/catalog/plateau_bonbons.png",
    },
    {
        "name": "Pralines amandes & noisettes",
        "slug": "pralines-amandes-noisettes",
        "category_slug": "chocolat",
        "description": "Chocolat croquant aux amandes et noisettes caramélisées. Coffret prestige.",
        "price": "18.50",
        "stock": 25,
        "image_url": "/catalog/chocolat_aux_noix.png",
    },
    {
        "name": "Chocolat chaud épices — tablette",
        "slug": "chocolat-chaud-epices",
        "category_slug": "chocolat",
        "description": "Tablette à fondre, cannelle et cardamome. Pour un chocolat chaud d'iftar.",
        "price": "8.90",
        "stock": 55,
        "image_url": "/catalog/chocolat_coffret_bleu.png",
    },
    {
        "name": "Coffret chocolat Ramadan — 16 pièces",
        "slug": "coffret-chocolat-ramadan-16",
        "category_slug": "chocolat",
        "description": "Assortiment chocolats (dattes, pistache, noix, orange). Idéal en cadeau.",
        "price": "26.90",
        "stock": 20,
        "image_url": "/catalog/coffret_chocolat_assorti.png",
    },
]


class Command(BaseCommand):
    help = "Seed catalog with a Ramadan Middle East pâtisserie selection (idempotent)."

    def handle(self, *args, **options):
        from catalog.models import Category, Product

        self.stdout.write("Disabling existing catalog...")
        Category.objects.all().update(is_active=False)
        Product.objects.all().update(is_active=False)

        self.stdout.write("Upserting categories...")
        category_by_slug = {}
        for c in RAMADAN_CATEGORIES:
            obj, _ = Category.objects.update_or_create(
                slug=c["slug"],
                defaults={
                    "name": c["name"],
                    "description": c["description"],
                    "is_active": True,
                },
            )
            category_by_slug[c["slug"]] = obj

        self.stdout.write("Upserting products...")
        for p in RAMADAN_PRODUCTS:
            Product.objects.update_or_create(
                slug=p["slug"],
                defaults={
                    "category": category_by_slug[p["category_slug"]],
                    "name": p["name"],
                    "description": p["description"],
                    "price": p["price"],
                    "stock": p["stock"],
                    "is_active": True,
                    "image_url": p["image_url"],
                },
            )

        self.stdout.write(self.style.SUCCESS("Ramadan catalog seeded successfully."))
